const API_URL = "http://40.76.245.64:8000/";
const IMAGE_BASE_URL = "http://40.76.245.64:8000";

// const API_URL = "http://localhost:8000/";
// const IMAGE_BASE_URL = "http://localhost:8000";

const AREAS_URL = "conservation-area/";
const DESTINATIONS_URL = "tourist-destination/";

const ALL_URL = "all/";

const FAVORITES_URL = "favorite";
const VISITED_URL = "visited";

const USER_REVIEW_URL = "user-review/";
const REVIEWS_URL = "reviews/";

const USERS_URL = "users/";
const PROFILE_URL = "profile/";
const PROFILES_URL = "profiles/";

const AREAS_IMAGE_WIDTH = 600;
const AREAS_IMAGE_HEIGHT = 400;

const DESTINATIONS_IMAGE_WIDTH = 600;
const DESTINATIONS_IMAGE_HEIGHT = 400;

const REGION_IMAGE_WIDTH = 600;
const REGION_IMAGE_HEIGHT = 400;

const PROFILE_PHOTO_IMAGE_WIDTH = 600;
const PROFILE_PHOTO_IMAGE_HEIGHT = 400;

const REVIEW_IMAGE_WIDTH = 600;
const REVIEW_IMAGE_HEIGHT = 400;

const FIRST_PERCENTAGE = 0.285;

const SECOND_PERCENTAGE = 0.645;
const THIRD_PERCENTAGE = 0.07;

const TEXT_CONTAINER_PERCENTAGE = 0.09;
const IMAGE_IN_LIST_PERCENTAGE = 0.5;
const VERTICAL_IMAGE_IN_LIST_PERCENTAGE = 0.23;
const IMAGE_IN_REVIEW_PERCENTAGE = 0.2;
const REVIEWS_CONTAINER_PERCENTAGE = 0.22;

const SECRET = "SECRET_KEY";

export {
  API_URL,
  AREAS_URL,
  DESTINATIONS_URL,
  ALL_URL,
  FAVORITES_URL,
  VISITED_URL,
  USER_REVIEW_URL,
  REVIEWS_URL,
  USERS_URL,
  PROFILE_URL,
  PROFILES_URL,
  IMAGE_BASE_URL,
  AREAS_IMAGE_WIDTH,
  AREAS_IMAGE_HEIGHT,
  DESTINATIONS_IMAGE_WIDTH,
  DESTINATIONS_IMAGE_HEIGHT,
  REGION_IMAGE_WIDTH,
  REGION_IMAGE_HEIGHT,
  PROFILE_PHOTO_IMAGE_WIDTH,
  PROFILE_PHOTO_IMAGE_HEIGHT,
  REVIEW_IMAGE_WIDTH,
  REVIEW_IMAGE_HEIGHT,
  FIRST_PERCENTAGE,
  SECOND_PERCENTAGE,
  THIRD_PERCENTAGE,
  TEXT_CONTAINER_PERCENTAGE,
  IMAGE_IN_LIST_PERCENTAGE,
  VERTICAL_IMAGE_IN_LIST_PERCENTAGE,
  IMAGE_IN_REVIEW_PERCENTAGE,
  REVIEWS_CONTAINER_PERCENTAGE,
  SECRET,
};
