const API_URL = "http://40.76.245.64:8000/";
const IMAGE_BASE_URL = "http://40.76.245.64:8000";

const AREAS_URL = "conservation-area/";
const DESTINATIONS_URL = "tourist-destination/";

const AREAS_IMAGE_WIDTH = 600;
const AREAS_IMAGE_HEIGHT = 400;

const DESTINATIONS_IMAGE_WIDTH = 600;
const DESTINATIONS_IMAGE_HEIGHT = 400;

const REGION_IMAGE_WIDTH = 600;
const REGION_IMAGE_HEIGHT = 400;

const FIRST_PERCENTAGE = 0.285;
const SECOND_PERCENTAGE = 0.645;
const THIRD_PERCENTAGE = 0.07;

const TEXT_CONTAINER_PERCENTAGE = 0.09;
const IMAGE_IN_LIST_PERCENTAGE = 0.5;

export {
  API_URL,
  AREAS_URL,
  DESTINATIONS_URL,
  IMAGE_BASE_URL,
  AREAS_IMAGE_WIDTH,
  AREAS_IMAGE_HEIGHT,
  DESTINATIONS_IMAGE_WIDTH,
  DESTINATIONS_IMAGE_HEIGHT,
  REGION_IMAGE_WIDTH,
  REGION_IMAGE_HEIGHT,
  FIRST_PERCENTAGE,
  SECOND_PERCENTAGE,
  THIRD_PERCENTAGE,
  TEXT_CONTAINER_PERCENTAGE,
  IMAGE_IN_LIST_PERCENTAGE,
};
